### ISSUE TITLE
USER STORY: Create admin site 

### ISSUE THREAD

**Issue by AdrianaStoi** [AdrianaStoi/Taste-of-Romania#1]
EPIC : Backend Store Administration 

As a **store owner** I want to be able to **access an admin panel where I can view users, edit, delete, products, categories, orders, comments, and ratings and filter in the sections** so that I can **efficiently manage the store.**

**Acceptance Criteria**
* The admin should be able to access a user management dashboard or section from the admin panel.
* Within the admin panel, there should be clear options to select the sections such as Users, Comments, Rating, Categories, Profiles and Orders.

**Tasks**
- [x] Set up the Django admin interface by configuring it in the project's settings.
- [x] Run the createsuperuser management command to create an initial superuser account with administrative privileges.
- [x] Create class ProductAdmin and CategoryAdmin in admin.py
