### ISSUE TITLE
USER STORY: View product by category

### ISSUE THREAD

**Issue by AdrianaStoi** [AdrianaStoi/Taste-of-Romania#11]
EPIC: Product Categorization and Searching

As a **shopper** I want to be able to **view products by specific product category** so that I can **easily find the product I am looking for.**

**Acceptance Criteria**
* On the site's interface, there are clearly labeled links or options that should allow the user to access products categorized by specific categories.
* Clicking on a category should direct the user to a page that displays only products belonging to that category.

**Tasks**
- [x] Create “Category” custom model and create the categories in the admin panel. 
- [x] Add product categories on the home page in the navbar. Develop the functionality that, when a user clicks on a category, they are directed to a dedicated page displaying products associated with the selected category.
- [x] Add a GET request condition for “category” to the “all_products” function in views.py that filters the products by category.
