### ISSUE TITLE
USER STORY: Checkout as guest

### ISSUE THREAD

**Issue by AdrianaStoi** [AdrianaStoi/Taste-of-Romania#17]
EPIC <epic>

As a **shopper** I want to be able to **place an order without been logged in** so that I can **place an order without having to create an account.**

**Acceptance Criteria**
* After adding the products to cart the user can click to the bag and on Secure checkout 
* The user should be able to add the order details without having to login 

**Tasks**
- [x] Create checkout.html that includes the necessary form fields to enter the delivery information data. 
- [x] Create checkout views
- [x] Install crispy forms
