### ISSUE TITLE
USER STORY: Adding Payment

### ISSUE THREAD

**Issue by AdrianaStoi** [AdrianaStoi/Taste-of-Romania#18]
EPIC: Ordering and Checkout

As a **shopper** I want to be able to **enter my payment information** so that I can **check out and place the order allowing me to quickly place the order.**

**Acceptance Criteria**
* On the checkout html page the user should have the field to enter the payment details
* The user should be prompted with a message if the card is not valid.

**Tasks**
- [x] Implement stripe for the secure payment 
- [x] Use UI elements to collect card details
- [x] Use stripe webhooks and add stripe Javascript to the checkout.html file
