### ISSUE TITLE
USER STORY: Add, edit and delete comment

### ISSUE THREAD

**Issue by AdrianaStoi** [AdrianaStoi/Taste-of-Romania#22]
EPIC: Product Comment and Rating

As a **shopper and frequent site user** I want to be able to **add, edit, delete comments** so that I can **give my feedback on quality of products and the services offered by the store, edit my comments, and remove mistakes or inaccurate information.**

**Acceptance Criteria**
* When the user is logged in as a registered user, they can view the Comment form and submit a comment.
* Each comment should include information date and time of the comment, and options for the user to manage the comment (e.g., edit or delete buttons).
* Users should be informed when they perform and action as add, edit or delete a comment. 

**Tasks**
- [x]  Add an if condition to html template page and if the user is authenticated, they should have the “Leave a comment” form available.
- [x] For comment edit and delete, editcomment.html page and deletecomment.html page, create edit comment and delete comment functions in views.py
- [x]  Add the url paths to urls.py and add the links to the html templates.
- [x] Add success messages to notify the user of their performed actions (e.g. edit comment, delete comment).
