### ISSUE TITLE
USER STORY: Edit existing product

### ISSUE THREAD

**Issue by AdrianaStoi** [AdrianaStoi/Taste-of-Romania#26]
EPIC: Frontend Store Administration 

As a **store owner** I want to be able to **edit a product from the front-end site** so that I can **easily edit products details accordingly without having to access the backend.**

**Acceptance Criteria**
* When the store owner is logged in the should have the Edit a product option available when products are listed or when the access the single product page. 
* Only the store owner should be able to edit a product.
* Once the store owner saves the Edit product, they should be prompted with a success message.

**Tasks**
- [x] Create edit product view and edit_product.html page
- [x] Add edit option to product detail page 
- [x] Add success messages to notify the user of their performed actions
