### ISSUE TITLE
USER STORY: Delete existing product 

### ISSUE THREAD

**Issue by AdrianaStoi** [AdrianaStoi/Taste-of-Romania#27]
EPIC: Frontend Store Administration 

As a **store owner** I want to be able to **delete a product from the frontend site** so that **easily delete products that are no longer available without having to access the backend.**

**Acceptance Criteria**
* When the store owner is logged in the should have the Delete a product option available when products are listed or when the access the single product page. 
* Only the store owner should be able to delete a product.
* Once the store owner clicks on the Delete product, they should be prompted with a success message.

**Tasks**
- [ ] Create and implement delete product view 
- [ ] Add delete option to product detail page and also when the products are listed 
- [ ] Add success messages to notify the user of their performed actions
