### ISSUE TITLE
USER STORY: User Inquiry 

### ISSUE THREAD

**Issue by AdrianaStoi** [AdrianaStoi/Taste-of-Romania#31]
EPIC: User Login/Registration and Profile

As a **shopper** I want to be able to **submit an inquiry** so that I can **ask about my order status or inquiry about products on the site.**

**Acceptance Criteria**
* Registered user should have the option to create an inquiry from their account. 
* They should have a form that they can fill in with the necessary information

**Tasks**
- [x] Create Inquiry model
- [x] Create views.py and InquiryForm in forms.py
- [x] Create and implement form html template that displays the form
