### ISSUE TITLE
USER STORY: User Registration

### ISSUE THREAD

**Issue by AdrianaStoi** [AdrianaStoi/Taste-of-Romania#6]
EPIC: User Login, Registration and Profile 

As a **frequent site user** I want to be able to **register on the site** so that **have an account to place an order, keep an order history and provide feedback on the products.**

**Acceptance Criteria**
* There should be a visible and accessible "Register" option on the site.
* When the user clicks on "Register", they should be directed to a registration page that includes fields for entering username, email address and password.
* After successfully registering, the user should be prompted with a message on the page that they have registered successfully.

**Tasks**
- [ ] Add the Register option at the top right corner of the page on the navigation bar and style it accordingly.
- [ ] Add allauth library for handling user authentication, registration. 
- [ ] Add success messages to notify the user of their successful registration.
