### ISSUE TITLE
USER STORY: User Login and Logout

### ISSUE THREAD

**Issue by AdrianaStoi** [AdrianaStoi/Taste-of-Romania#7]
EPIC: User Login, Registration and Profile 

As a **frequent site user** I want to be able to **login or logout** so that **I can access my account information**

**Acceptance Criteria**
* The user should be able to easily login and logout from their account. 
* The options to login/logout should be visible on the site.
* The user should be prompted with a message when they login or logout.

**Tasks**
- [x] Implement a login functionality using allauth library that includes fields for entering a username and password and a "Login" button for initiating the login process and validating user credentials.
- [x] Integrate the login status display into the site's header, ensuring that users are always aware of their login status.
- [x] Implement logout functionality using allauth library.
- [x] Add success messages to notify the user of their action performed.
