### ISSUE TITLE
USER STORY: Access user Profile

### ISSUE THREAD

**Issue by AdrianaStoi** [AdrianaStoi/Taste-of-Romania#9]
EPIC: User Login, Registration and Profile

As a **registered user** I want to be able to **access my user profile page** so that I can **save my details for next purchases and view my orders.**

**Acceptance Criteria**
* When the user logs in and accesses their user profile page, they should see a section that displays their personal details, the option to edit them and their Order History.
* Each order in the list should include order information such as product name, date and time of purchase, price.

**Tasks**
- [x] Create a User Profile custom model. 
- [x] Create a User Profile account page using HTML and style it with CSS. 
- [x] To display the list of order use loops to iterate through the user's order and display them in a list.
